name: 'Weather Lambda Dev Deployment'

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  AWS_REGION : 'us-east-1'
  AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
  OPEN_WEATHER_API_ID: ${{ secrets.OPEN_WEATHER_API_ID }}
  JWKS_URI_ID: ${{ secrets.JWKS_URI_ID }}

permissions:
  contents: read
  pull-requests: read
  id-token: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  weatherLambdaDevDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
        env:
          AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install AWS CDK
        run: yarn add aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/GithubActionsProvider
          aws-region: us-east-1

      - name: Run Unit Tests
        run: yarn test

      - name: Run Integration Tests
        run: yarn integration
        env:
          AWS_ACCOUNT_NUMBER: ${{ env.AWS_ACCOUNT_NUMBER }}
          AWS_REGION: us-east-1

      - name: Deploy Dev
        shell: bash
        run: |
              echo "yarn deploy"
              yarn deploy
